### ISSUE TITLE
Unable to cast python instance to C++ type with running with coffea dask executor on CERN lxplus

### ISSUE THREAD

**Issue by patinkaew** [cms-nanoAOD/correctionlib#169]
I encountered the following error with running with coffea dask executor on CERN lxplus

```
Traceback (most recent call last):       ] | 50% Completed |  2min 57.0ss
  File "/eos/home-p/pinkaew/research/online-offline-jec/process.py", line 353, in <module>
    processing(args, configs, runner, fileset, treename="Events", 
  File "/eos/home-p/pinkaew/research/online-offline-jec/process.py", line 83, in processing
    out = runner(fileset, treename=treename, processor_instance=processor_instance)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 1366, in __call__
    wrapped_out = executor(chunks, closure, None)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 735, in __call__
    else _decompress(work.result())
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/distributed/client.py", line 275, in result
    raise exc.with_traceback(tb)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 197, in __call__
    out = self.function(*args, **kwargs)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 990, in automatic_retries
    raise e
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 978, in automatic_retries
    return func(*args, **kwargs)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 1238, in _work_function
    raise type(e)(str(e) + file_trace).with_traceback(
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 1235, in _work_function
    out = processor_instance.process(events)
  File "/tmp/dask-worker-space/worker-61h2nuka/processor.zip/processor/processor.py", line 292, in process
  File "/tmp/dask-worker-space/worker-61h2nuka/processor.zip/processor/selectorbase.py", line 14, in __call__
  File "/tmp/dask-worker-space/worker-61h2nuka/processor.zip/processor/selector.py", line 194, in apply_event_wrapped_physics_object_selector
  File "/tmp/dask-worker-space/worker-61h2nuka/processor.zip/processor/selector.py", line 327, in apply_jet_veto_map
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/correctionlib/highlevel.py", line 96, in evaluate
    return self._base.evaluate(*args)  # type: ignore
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

correctionlib is used to read in json files to apply jet veto maps. This is called inside ```process``` method of ```coffea.processor```. I run this on lxplus7104, LCG102, HTCondor v9.0.

This might be an issue with version shipped with LCG102. I also run on lxplus7104, LCG102 with Iterative and failed with the same error.

Here is my implementation of wrapper class for jet veto map:
```
class JetVetoMap(SelectorABC):
    def __init__(self, jet_veto_map_json_path, jet_veto_map_correction_name,
                 jet_veto_map_year, jet_veto_map_type="jetvetomap", name=""):
        super().__init__()
        if jet_veto_map_json_path:
            assert len(name) and name != None, "must provide unique name"
            corr = correctionlib.CorrectionSet.from_file(jet_veto_map_json_path)[jet_veto_map_correction_name]
            self._jet_veto_map = partial(corr.evaluate, jet_veto_map_year, jet_veto_map_type)
        else:
            self._jet_veto_map = None
            self.off()
        self._name = name
    def __str__(self):
        return "{}: jet veto map".format(self._name)
    def apply_jet_veto_map(self, jets):
        if not self._jet_veto_map:
            return jets
        # flatten and unflatten (this is required for correctionlib API)
        jets_flat = ak.flatten(jets)
        counts = ak.num(jets)
        jets_flat_phi = jets_flat.phi # wrap phi in (-pi, pi]
        jets_flat_phi = ak.where(jets_flat_phi <= -np.pi, 2*np.pi + jets_flat_phi, jets_flat_phi)
        jets_flat_phi = ak.where(jets_flat_phi > np.pi, -2*np.pi + jets_flat_phi, jets_flat_phi)
        mask_flat = (self._jet_veto_map(jets_flat.eta, jets_flat_phi) == 0)
        mask = ak.unflatten(mask_flat, counts=counts)
        return jets[mask]
    apply = apply_jet_veto_map
```
I

**Comment by patinkaew** [comment]
This is resolved. I will leave this issue here for record. From https://gist.github.com/nsmith-/8d3d41aaffda92148ebc7bfcc5c827f5, converting to ```numpy.array``` solves the problem.

**Comment by nsmith-** [comment]
Great! Indeed, in #141 we added an auto-conversion internally that should be in version [2.2](https://github.com/cms-nanoAOD/correctionlib/releases/tag/v2.2.0) and up. What version do you have available?

**Comment by patinkaew** [comment]
It is version 2.1.0 which is shipped with LCG102 and LCG103 
```
$. /cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/setup.sh
$ python -c "import sys, correctionlib; print(sys.executable); print(correctionlib.__version__)"
/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/bin/python
2.1.0

$. /cvmfs/sft.cern.ch/lcg/views/LCG_103/x86_64-centos7-gcc11-opt/setup.sh
$python -c "import sys, correctionlib; print(sys.executable); print(correctionlib.__version__)"
/cvmfs/sft.cern.ch/lcg/views/LCG_103/x86_64-centos7-gcc11-opt/bin/python
2.1.0
```

**Comment by nsmith-** [comment]
Ok, thanks for checking. Hopefully newer LCG will have this patch
