### ISSUE TITLE
Assertion error in from_uproot_THx with a TH2F

### ISSUE THREAD

**Issue by jmhogan** [cms-nanoAOD/correctionlib#202]
Hi folks. When attempting to read a TH2F from convert.from_uproot_THx I am getting an AssertionError that might represent a bug. 

~~~
[jmanagan@cmslpc132 ~]$ python3
Python 3.9.6 (default, Dec 16 2021, 17:01:31) 
[GCC 10.3.0] on linux
>>> from correctionlib import convert
>>> corr = convert.from_uproot_THx("SF_Ele50_Ele115_2016.root:abseta_pt_ratio")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/py3-correctionlib/2.1.0-18f6d1dfcf4c205c38d543f9ef2a014b/lib/python3.9/site-packages/correctionlib/convert.py", line 30, in from_uproot_THx
    return from_histogram(uproot.open(path))
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/py3-correctionlib/2.1.0-18f6d1dfcf4c205c38d543f9ef2a014b/lib/python3.9/site-packages/correctionlib/convert.py", line 139, in from_histogram
    "data": build_data(hist.values(), hist.axes, variables),
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/py3-correctionlib/2.1.0-18f6d1dfcf4c205c38d543f9ef2a014b/lib/python3.9/site-packages/correctionlib/convert.py", line 107, in build_data
    "edges": [edges(ax) for ax in axes[:i]],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/py3-correctionlib/2.1.0-18f6d1dfcf4c205c38d543f9ef2a014b/lib/python3.9/site-packages/correctionlib/convert.py", line 107, in <listcomp>
    "edges": [edges(ax) for ax in axes[:i]],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/py3-correctionlib/2.1.0-18f6d1dfcf4c205c38d543f9ef2a014b/lib/python3.9/site-packages/correctionlib/convert.py", line 62, in edges
    assert isinstance(b, tuple)
AssertionError
~~~

The ROOT file can be downloaded from here: https://jmhogan.web.cern.ch/jmhogan/SF_Ele50_Ele115_2016.root

**Comment by nsmith-** [comment]
I now understand the issue is that the uproot version installed inside CMSSW (which I assume is the environment you are using, given the `/cvmfs/` paths) is not compatible with correctionlib. In principle, the dependency `uproot>=4.0.4` is specified but CMSSW externals are not respecting this. Which version of CMSSW are you in?
Perhaps a quick fix is to do `python3 -m pip install --user "uproot>=4.0.4"`

**Comment by nsmith-** [comment]
I can confirm this is a dependency issue, where CMSSW is not respecting the necessary uproot version:
```
$ python3
Python 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from correctionlib import convert
>>> corr = convert.from_uproot_THx("https://jmhogan.web.cern.ch/jmhogan/SF_Ele50_Ele115_2016.root:abseta_pt_ratio")
>>> import rich
>>> rich.print(corr)
📈 abseta_pt_ratio (v0)
No description
Node counts: MultiBinning: 1
╭───── ▶ input ──────╮ ╭─────── ▶ input ───────╮
│ axis0 (real)       │ │ axis1 (real)          │
│ No description     │ │ No description        │
│ Range: [-2.5, 2.5) │ │ Range: [50.0, 1000.0) │
╰────────────────────╯ ╰───────────────────────╯
╭─── ◀ output ───╮
│ out (real)     │
│ No description │
╰────────────────╯
```

**Comment by jmhogan** [comment]
super delayed thanks @nsmith- !
