### ISSUE TITLE
`Value error, Edges array contains non-finite values`

### ISSUE THREAD

**Issue by connorpa** [cms-nanoAOD/correctionlib#262]
With correctionlib 2.6.1, in `jsonpog-integration/POG/MUO/2023_Summer23`, running the following leads to a crash:
```sh
% correction summary muon_Z.json.gz
──────────────────────────────── Corrections in file muon_Z.json.gz ────────────────────────────────
Traceback (most recent call last):
  File "/home/connorpa/.micromamba/envs/DAS/bin/correction", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/connorpa/.micromamba/envs/DAS/lib/python3.12/site-packages/correctionlib/cli.py", line 192, in main
    retcode: int = args.command(console, args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/connorpa/.micromamba/envs/DAS/lib/python3.12/site-packages/correctionlib/cli.py", line 66, in summary
    cset = model_auto(open_auto(file))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/connorpa/.micromamba/envs/DAS/lib/python3.12/site-packages/correctionlib/highlevel.py", line 48, in model_auto
    return correctionlib.schemav2.CorrectionSet.model_validate(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/connorpa/.micromamba/envs/DAS/lib/python3.12/site-packages/pydantic/main.py", line 568, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 77138 validation errors for CorrectionSet
corrections.0.data.Binning.content.0.Binning.edges.function-after[validate_nonuniform_edges(), list[union[float,literal['inf','+inf','-inf']]]]
  Value error, Edges array contains non-finite values: [15.0, 20.0, 25.0, 30.0, 40.0, 50.0, 60.0, 120.0, inf]. Replace infinities with 'inf' or '-inf'. NaN is not allowed. [type=value_error, input_value=[15.0, 20.0, 25.0, 30.0, ... 50.0, 60.0, 120.0, inf], input_type=list]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error
corrections.0.data.Binning.content.0.Binning.edges.UniformBinning
  Input should be a valid dictionary or instance of UniformBinning [type=model_type, input_value=[15.0, 20.0, 25.0, 30.0, ... 50.0, 60.0, 120.0, inf], input_type=list]
    For further information visit https://errors.pydantic.dev/2.8/v/model_type
corrections.0.data.Binning.content.0.Binning.content
  Assertion failed,  [type=assertion_error, input_value=[{'nodetype': 'category',...': 0.967926623192985}]}], input_type=list]
    For further information visit https://errors.pydantic.dev/2.8/v/assertion_error
corrections.0.data.Binning.content.0.MultiBinning.nodetype
  Input should be 'multibinning' [type=literal_error, input_value='binning', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/literal_error
corrections.0.data.Binning.content.0.MultiBinning.inputs
  Field required [type=missing, input_value={'nodetype': 'binning', '...85}]}], 'flow': 'error'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing

...
```
Reading the tables with example scripts in https://gitlab.cern.ch/cms-nanoAOD/jsonpog-integration still seems to work. Not a major issue, but investigating the tables from the command line would be useful...

**Comment by nsmith-** [comment]
This is fixed by adding the command-line argument `--ignore-float-inf` as added in #257 (v2.6.2+)

**Comment by connorpa** [comment]
Just out of curiosity: why can that no be the default behaviour? Adding such an option to the command line is heavy and counter-intuitive. Why not reverse the logic and add a option `--fail-on-infinite`? (which would probably be used much less often?)

**Comment by nsmith-** [comment]
Although it's a fair point, the long-term plan is to remove completely floating point infinity from the schema, per the decision of #226, so in the long term it should be an error. We turn it off now because the old evaluator codes are not forwards-compatible and break on seeing `"inf"` in the json. So we have to wait for a hard migration point and move all evaluators to 2.6+
